#! /usr/bin/env python

import sys
import argparse
import subprocess

class Device(object):

    fields = ["label:", "type:", "usage:", "is mounted:"]

    def __init__(self, path):
        self.path = path
        self.getinfo()
        return

    def __repr__(self):
        mnt = "*" if int(self.attr["is mounted:"]) else "_"
        s = "{0:12s}{1:16s}{2:6s}{3:10s}{4:>3s}".format(self.path,
                                            self.attr["label:"],
                                            self.attr["type:"],
                                            self.attr["usage:"],
                                            mnt)
        return s

    def __eq__(self, other):
        for k in self.attr:
            if other in (self.path, self.attr["label:"]):
                return True
        return False

    def getinfo(self):
        self.attr = {}
        info = subprocess.check_output(["udisks", "--show-info", self.path],
                                       universal_newlines=True)
        for line in filter(lambda s: s[2:4] != "  ", info.split("\n")):
            fld = line[:31].strip()
            if fld in self.fields:
                self.attr[fld] = line[31:].strip()

    def isdrive(self):
        return self.attr.get("usage:", "") == "filesystem"

    def mount(self):
        return subprocess.call(["udisks", "--mount", self.path])

    def unmount(self):
        return subprocess.call(["udisks", "--unmount", self.path])


class UserError(Exception):
    def __init__(self, msg):
        print msg
        sys.exit(1)


def get_devices():
    dlist = []
    enumf = subprocess.check_output(["udisks", "--enumerate-device-files"],
                                    universal_newlines=True)
    for name in filter(lambda s: s.count("/") == 2, enumf.split("\n")):
        dev = Device(name)
        if dev.isdrive():
            dlist.append(dev)
    return dlist

def print_devices(devices):
    for dev in devices:
        print(dev)
    return

def main():

    parser = argparse.ArgumentParser(description="Mount and unmount filesystems")
    parser.add_argument("action", help="action to undertake",
                        choices=("mount", "unmount", "list"), nargs="?")
    parser.add_argument("fs", help="identifier for the filesystem to operate on",
                        nargs="?")
    args = parser.parse_args()

    devices = get_devices()

    if args.action is None or args.action == "list":
        print_devices(devices)
        sys.exit(0)

    if args.action in ("mount", "unmount"):
        if args.fs is None:
            raise UserError("Must provide a device name in order to mount")
        elif args.fs not in devices:
            raise UserError("Device \"{0}\" not found".format(args.fs))
        elif args.action == "mount":
            for dev in devices:
                if dev == args.fs:
                    ret = dev.mount()
        elif args.action == "unmount":
            for dev in devices:
                if dev == args.fs:
                    ret = dev.unmount()
                    if dev not in get_devices():
                        print("{0} unmounted".format(dev.attr["label:"]))

if __name__ == "__main__":
    main()

